### ISSUE TITLE
Email as a bullet point protocol about the FSFE + OSI  meeting before SFSCON

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/documentation#5]

**Comment by Piiit** [comment]
@ohnewein Can you please check the document I've send you and move this task to done if OK

**Comment by ohnewein** [comment]
@Piiit I have send you my comments.

**Comment by Piiit** [comment]
@ohnewein Done. Please re-test :-)

**Comment by ohnewein** [comment]
@ohnewein send the mail
